### ISSUE TITLE
Manual import of existing EUI thumbnails

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#14]
Import thumbnail images into existing Dataset records, register as a standard uploaded file (create a file uuid for), with the "thumbnail" attribute set to true.

**Comment by shirey** [comment]
Existing thumbnails are here: https://github.com/hubmapconsortium/ccf-ui/tree/main/projects/ccf-eui/src/assets/thumbnails

**Comment by yuanzhou** [comment]
Update: the folder contains both Sample and Dataset thumbnails currently, we are only handling it for Dataset at this point.

**Comment by yuanzhou** [comment]
Update: @bherr2 will change the parsing in ccf-ui to prefix with `dataset.uuid` in the thumbnail filename: https://github.com/hubmapconsortium/ccf-ui/blob/main/projects/ccf-database/src/lib/hubmap/hubmap-data.ts#L328-L351

And I'll parse the uuid to register all the dataset thumbnails once they are in place.

**Comment by yuanzhou** [comment]
Update: registered the 40 dataset thumbnail images from Bruce on TEST and added instructions to this issue: https://github.com/hubmapconsortium/ccf-ui/issues/624#issuecomment-887604766

Code is available at https://github.com/hubmapconsortium/manual-data-ingest/tree/master/ingest-thumbnails
