### ISSUE TITLE
Validate for required DOI info before publication

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#206]
For PRIMARY Datasets only (datasets connected directly to a sample, not another dataset):
In the ingest-api publication endpoint, `/datasets/<dataset id>/publish` before publishing the dataset verify that it has required information to generate a DOI which includes:
 - valid `donor.metadata`
 - at least one `dataset.contributors`
 - at least one `dataset.contacts`
 - other?

On validation failure, return a 400 status code with a message explaining why the validation failed.

**Comment by DerekFurstPitt** [comment]
For pre-publish validation, we shoudl also validate the existence of `donor.metadata.organ_donor_data` or donor.metadata.living_donor_data`, one of them must be present but not both. we use them to generate `dataset.title` which is used for DOI registration. We should also validate the `dataset.status` to be "Published" before any DOI work, the DOI script handles this but for the sake of pre-publish validation, we should do this again
