### ISSUE TITLE
Update full-path endpoint to allow for non-consortium users to access non-protected published datasets

### ISSUE THREAD

**Issue by jpuerto-psc** [hubmapconsortium/ingest-api#233]

**Comment by shirey** [comment]
@jpuerto-psc Is this still needed (maybe this happened under a different issue)?  If so, which endpoint?-- It looks like both `GET ingest-api/datasets/<ds_uuid>/file-system-abs-path` and `POST ingest-ap/datasets/<ds_uuid>/file-system-abs-path` are open to all now.

**Comment by jpuerto-psc** [comment]
@shirey - I think this was taken care of by the POST endpoint. Closing now.

**Comment by jpuerto-psc** [comment]
Apologies I misread this issue. Yes this is still needed and I think rather urgently since we are expecting non-consortium users to be able to access non-protected published data via Workspaces.
