### ISSUE TITLE
Handle 404 for datasets/{uuid}/file-system-abs-path

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-api#24]
From Joel:
>  I have a very low priority bug report on ingest-api.  When the endpoint datasets/{uuid}/file-system-abs-path is hit with a value which is not a real uuid, the response happily sends back a path string constructed with whatever was sent.  For example, datasets/HBM568.NGPL.345/file-system-abs-path returns '/hive/hubmap-test/data/consortium/University of Florida TMC/HBM568.NGPL.345' .

> I've worked around it in my code so this isn't blocking anything, but I thought I'd report it.  Worst case, someone could use it to get the endpont to return an arbitrary path.

From Bill:
> If the ID doesn’t exist it should send back a 404 status.  If the ID is not a UUID (HuBMAP ID or Submission ID) but does exist it should be converted to a uuid in the path.

**Comment by shirey** [comment]
Please verify if this is still broken.
