### ISSUE TITLE
Autogenerate dataset name field at publication

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#25]
Create a dataset name, store it in the Dataset.title field.  Based on this template:
"\<Assay Type\> data from the \<organ name\> of a \<years old\> year old \<race\> \<sex\>.
For Example: "Bulk ATAC-seq data from the liver of a 63 year old white male."

**Comment by yuanzhou** [comment]
Note, will need to convert the actual Dataset.data_types values to the corresponding descriptions in this yaml: https://github.com/hubmapconsortium/search-api/blob/test-release/src/search-schema/data/definitions/enums/assay_types.yaml

**Comment by yuanzhou** [comment]
This is related to https://github.com/hubmapconsortium/entity-api/issues/152
