### ISSUE TITLE
Add /datasets/<ent_uuid>/file-system-abs-path route

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#32]
Add a method to ingest-api to return the absolute path to a dataset given the dataset uuid.

The helper method `ingest_file_helper.get_dataset_directory_absolute_path` should be helpful with this.

**Comment by yuanzhou** [comment]
Isn't this method already there? https://github.com/hubmapconsortium/ingest-api/blob/test-release/src/app.py#L301
