### ISSUE TITLE
Add email notification functionality

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#328]
@kburke 

We have the need to send an email to the help desk when the "submit" button is pushed on Uploads or Datasets in the Ingest UI.  Currently these buttons are wired to the [ingest-ui notify-slack](https://github.com/hubmapconsortium/ingest-api/blob/f9f2c2353a46f94fc519e33e4be1606a70e4401f/src/app.py#L299) endpoint.  

Add an option to send an email via this endpoint, if the optional parameter `send_to_email` is included additionally send the same message that is sent to Slack via email to the address specified in `send_to_email`.  The other parameters needed to send the email:
                                                                                              
 - MAIL_SERVER 
 - MAIL_PORT
 - MAIL_USE_TLS
 - MAIL_USERNAME                                                                                                    
 - MAIL_PASSWORD 
 - MAIL_DEFAULT_SENDER
 - MAIL_DEBUG 

should be included via in the standard app.cfg file.

The Slack notification functionality should remain the same (and always sent), with the new email notification functionality being optional. Additionally, change the name of the endpoint from `notify-slack` to `notify`, coordinate with @BirdMachine (Jes) to release a version of Ingest UI at the same time that supports the new endpoint name.

**Comment by kburke** [comment]
I have modified the response when the renamed endpoint is successful in both posting a Slack notification and sending an email to include summary for each, as below.

I'm not sure if this is relevant to @BirdMachine for UI revisions.
```
{
    "Email": {
        "email_recipient_list": "['kburke@pitt.edu']",
        "message": "notification posting from Postman by KB at Fri Jun 23 2023 10:43:22 GMT-0400 (Eastern Daylight Time).",
        "user_email": "KBURKE@pitt.edu",
        "user_name": "Karl Burke"
    },
    "Slack": {
        "channel": "data-testing-notifications",
        "message": "notification posting from Postman by KB at Fri Jun 23 2023 10:43:22 GMT-0400 (Eastern Daylight Time).",
        "user_email": "KBURKE@pitt.edu",
        "user_name": "Karl Burke"
    }
}
```

**Comment by kburke** [comment]
See [Comment on PR about using Dev for UI revisions, then coordinating with others on Test](https://github.com/hubmapconsortium/ingest-api/pull/332#issuecomment-1604600040).
