### ISSUE TITLE
generate `metadata.json` file at publication

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#375]
Data users have requested a json version of the associated Dataset metadata to be included with Dataset downloads.  To facilitate this we'll generate a `metadata.json` into the Dataset directory at publication time.

During the [ingest-api /datasets/<identifier>/publish/](https://github.com/hubmapconsortium/ingest-api/blob/821803ca927e3434aa3af7396b2e6ee175fe1e42/src/app.py#L717C13-L717C43) endpoint execution, for primary datasets only convert the `ingest_metadata.metadata` field to json and write the json into a file `metadata.json` at the top level of the dataset directory.
  - If the dataset is primary, identified by the [is_primary variable](https://github.com/hubmapconsortium/ingest-api/blob/821803ca927e3434aa3af7396b2e6ee175fe1e42/src/app.py#L739)
  - Retrieve the `ingest_metadata` field encoded in string from the dataset at the same time that [other dataset info is retrieved](https://github.com/hubmapconsortium/ingest-api/blob/821803ca927e3434aa3af7396b2e6ee175fe1e42/src/app.py#L798-L805)
  - Convert `ingest_metadata` to a python dict, this should be done with a method similar to [entity-api convert_str_literal function](https://github.com/hubmapconsortium/entity-api/blob/a832a906124623a889a943c15ff7c8d93f2bb068/src/schema/schema_manager.py#L1666)- ask Zhou for advice on how to convert and possibly copy this function to the hubmap-commons package and use from there (no need to use from hubmap-commons in entity-api at this point, but can be done later)
  - At a point before the [dataset directory is moved](https://github.com/hubmapconsortium/ingest-api/blob/821803ca927e3434aa3af7396b2e6ee175fe1e42/src/app.py#L831) (only moved if consortium level, but write the file whether moved or not), write the contents of `ingest_metadata.metadata` as json to `metadata.json` in the dataset directory.  The absolute path to the dataset directory can be found with a call to `ingest_helper.__dataset_directory_absolute_path(adataset_data_access_level, dataset_group_uuid, dataset_uuid, False)`

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/ingest-api/pull/388
