### ISSUE TITLE
Open endpoints that drive ingest board to public

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#376]
@bhonick Would like to generate reports using a BI tool which will retrieve dataset and upload status from the same endpoints that we use to drive the Data Ingest Board.  The BI tool will consume json, but cannot sent an authorization token, so we need to remove the requirement to provide a valid token for these endpoints.  These endpoints will be open to the world without any need for authorization (no token required)-- Per Phil, this is fine to open these endpoints for public access.

Change the authorization on the ingest-api endpoints used for retrieving [dataset status GET /datasets/data-status](https://github.com/hubmapconsortium/ingest-api/blob/821803ca927e3434aa3af7396b2e6ee175fe1e42/src/app.py#L1525C13-L1525C34) and [upload GET /uploads/data-status](https://github.com/hubmapconsortium/ingest-api/blob/821803ca927e3434aa3af7396b2e6ee175fe1e42/src/app.py#L1544) to require no token at all.

**Comment by yuanzhou** [comment]
Addressed via PR https://github.com/hubmapconsortium/gateway/pull/277 and released via PR https://github.com/hubmapconsortium/gateway/pull/278

**Comment by shirey** [comment]
When this has been completed please notify @bhonick

**Comment by yuanzhou** [comment]
@bhonick the two endpoints are open now, no token is required
```
GET https://ingest.api.hubmapconsortium.org/datasets/data-status
GET https://ingest.api.hubmapconsortium.org/uploads/data-status
```

**Comment by bhonick** [comment]
Excellent, thank you @yuanzhou , @shirey
