### ISSUE TITLE
Update ingest-api routes/validation to use UBKG

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ingest-api#410]
There are several places in ingest-api routes/validation where data that should come from UBKG has been hard coded because that data did not exist in UBKG. This issue will be fixed in UBKG with https://github.com/x-atlas-consortia/hs-ontology-api/pull/58 which will allow this data to no longer be hardcoded.

This card will involve pulling that data from UBKG replacing the hard coded data that is in ingest-api routes/validation

**Comment by ChuckKollar** [comment]
Alan Simmons 11/15/23

https://ontology-api.dev.hubmapconsortium.org/valueset?parent_sab=HUBMAP&parent_code=C000012&child_sabs=HUBMAP

Provenance entities are available in HUBMAP in DEV
[
{
"code": "C040001",
"sab": "HUBMAP",
"term": "Dataset"
},
{
"code": "C000008",
"sab": "HUBMAP",
"term": "Organ"
},
{
"code": "C040002",
"sab": "HUBMAP",
"term": "Sample"
},
{
"code": "C040003",
"sab": "HUBMAP",
"term": "Publication Entity"
},
{
"code": "C040004",
"sab": "HUBMAP",
"term": "Upload"
},
{
"code": "C040005",
"sab": "HUBMAP",
"term": "Antibodies"
},
{
"code": "C040006",
"sab": "HUBMAP",
"term": "Contributors"
}
]

**Comment by yuanzhou** [comment]
Addressed via https://github.com/x-atlas-consortia/hs-ontology-api/pull/58 and redeployed on DEV and PROD.
