### ISSUE TITLE
Add full provenance info to metadata.json files

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#411]
Jonathan has requested that the full provenance metadata information be included in the metadata.json files that are currently being generated (which only include the actual data metadata that we obtain during dataset ingest).

Both for the endpoint that will generate a metadata.json file for a dataset, and for the endpoint at publication time change the contents of the metadata.json file. Include the full json response of the entity-api `/entities/<dataset id>` endpoint and add to that lists of the full responses (from entity-api) for all associated `donors`, `organs` and `samples`. 

See example cypher below to obtain the uuids of these associated entities, then make calls to the entity-api `/entities/<entity id>` endpoint to get the json for inclusion in the list of each type. These will be included as an array with one item per entity-api response with the keys: `donor`, `organ`, `sample`.

```
Sample IDs:
match (ds:Dataset {uuid:'<dataset uuid>'})<-[*]-(s:Sample) where not s.sample_category = 'organ' return distinct s.uuid;

Organ IDs:
match (ds:Dataset {uuid:'<dataset uuid>'})<-[*]-(o:Sample) where o.sample_category = 'organ' return distinct o.uuid;

Donor IDs:
match (ds:Dataset {uuid:'<dataset uuid>'})<-[*]-(d:Donor) return distinct d.uuid;
```

Also, of note-- the entity-api endpoint `/datasets/<dataset id>/organs` could be used to get the organ information, but similar endpoints don't exist for Sample and Donor... A new endpoint will be created in entity-api to retrieve the 'organ', 'donor', and 'sample' uuids (see: https://github.com/hubmapconsortium/entity-api/issues/604).

So, adding arrays to the standard entity-api endpoint json response for `/entities/<dataset id>` for each of `donors`, `organs` and `samples` is what we need written to the metadata.json file now, instead of just the dataset.ingest_metadata.metadata, as it is now. 

Attached example metadata.json for fa238ec2a83302fb4af92442c3683a23, with added donors, samples and organs

[fa238ec2a83302fb4af92442c3683a23-sample-metadata.json](https://github.com/hubmapconsortium/ingest-api/files/14057482/fa238ec2a83302fb4af92442c3683a23-sample-metadata.json)

Remember that this change must be effected in two endpoints in `ingest-api`:
1) the endpoint that publishes
2) the endpoint that creates the 

Remember to make the necessary changes to the `OpenAPI.yaml` for `ingest-api`.

**Comment by ChuckKollar** [comment]
See Commit: https://github.com/hubmapconsortium/ingest-api/commit/6244ccd5707f74eb8c84489a25779507c8fa83f1

**Comment by ChuckKollar** [comment]
This Issue has been amended to use the two endpoints (donor and sample) of https://github.com/hubmapconsortium/entity-api/issues/604 along with the existing entity-api endpoint /datasets/<dataset id>/organs.

Method:
1) Make a call to /entities/<dataset id> saving the full information to the metadata.json file,
2) In the object returned from 1) create three new keys 'organs', 'samples', 'donors' which will hold an array.
3) fill the keys created in 2) with the data returned from the entity-api endpoints corresponding to the three keys.
4) save the json as before (in the matadata.json file) but with the content created in the steps above.

Remember that this change must be effected in two endpoints in ingest-api:
1) the endpoint that publishes
2) the endpoint that creates the

**Comment by yuanzhou** [comment]
@ChuckKollar based on our conversation, here is what I think will be a simpler and more efficient solution:
- In entity-api, create two new endpoints `/datasets/<id>/donors` and `/datasets/<id>/samples`, implementation is similar to the existing `/datasets/<id>/organs` but with modified neo4j queries so we return all the entity dicts rather than just uuids. And we can add uuid filtering to only return uuids later if needed, will be very easy.

- In the ingest-api, you'll then just need to call the three endpoints in entity-api to get back all prov info of donors, samples, and organs to be included into the final response.

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/ingest-api/pull/497
