### ISSUE TITLE
Fix bug in validation code

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ingest-api#490]
There is a but in the validation code in ingest-api main which is caused by a the header of a call to entity-api not being a dict.

There is one other problem in ingest-api which is caused by the fact that ingest_validation_tools hard codes the entity-api url to that in PROD in the file upload.py _cedar_url_checks().

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/ingest-api/pull/488

**Comment by ChuckKollar** [comment]
The issue of ingest_validation_tools only working in PROD because it hardwires a call to entity-prod in the code, is not fixed here. The ingest_validation_tools should pull the first part of the path from a config file. I believe that the authors are working on this.

**Comment by yuanzhou** [comment]
@ChuckKollar thanks for tracking the issue with this new card. Yes we'll have to wait until the PSC team addresses this issue in the Ingest Validation Tools.
