### ISSUE TITLE
Add endpoint `privs/has-data-admin`

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#514]
Replicate/port `/privs/has-data-admin` from SenNet ingest-api

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/ingest-api/pull/530

**Comment by ChuckKollar** [comment]
Related PR: https://github.com/hubmapconsortium/gateway/pull/306

**Comment by ChuckKollar** [comment]
The endpoint has been modified to send a 401 if the "User's token is not valid" (as per the ingest-api-spec.yaml file). For a valid token it will return the json {'has_data_admin_privs': true/false}.
