### ISSUE TITLE
UMLS File download list endpoint

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#542]
Create a new endpoint `GET /umls-download-file-list` which will return a list of files in the new `umls-download` directory available via the assets service, defined in [gateway issue #308](https://github.com/hubmapconsortium/gateway/issues/308).  Response is a json list of file information including:
  - file name
  - human readable file size ( like 768M, 321K, etc . . .)
  - a description of the file (optional, see below)

If the file `file-descriptions.json` is included in the directory use the descriptions included in the file for the description field of returned file information.  If a file is not included, return an empty description.  Do not include this `file-descriptions.json` file in the response list of files.

Include all other files at the top level directory in the response.  For this MVP there is no need to include sub-directories and files at this point.

Example response:
```
[
  {
     "name": "test-file1.txt",
     "size": "10M",
     "description": "A test file..."
  },
  {
     "name": "test-file2.txt",
     "size": "894M",
     "description": "A second test file..."
  },
  {
     "name": "test-file3.txt",
     "size": "456K"
  },
  . . .
]
```

Example file-descriptions.json:
```
[
   "test-file1.txt": "A test file...",
   "test-file2.txt": "A second test file..."
]
```

**Comment by yuanzhou** [comment]
Update 4/16/2024

@DerekFurstPitt you would rename to `GET /ubkg-download-file-list` which will return a list of files in the new `ubkg-download` directory.

**Comment by yuanzhou** [comment]
Will return the bytes number directly and let the UI to make them human readable. Library like https://github.com/sindresorhus/pretty-bytes is very handy.
