### ISSUE TITLE
Updates to support Data Ingest Board datasets/uploads bulk editing

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-api#568]
These are the corresponding backend changes required by https://github.com/x-atlas-consortia/data-ingest-board/pull/198

- ~~New endpoints (`PUT /datasets` and `PUT /uploads`) to handle the bulk updating of entities - https://github.com/sennetconsortium/ingest-api/pull/449/files#diff-dbbd81613f45e75c24d247a0a00eaf8bc018218b14771a16b30b182368852c6e~~

- Modifying the results from the `/data-status` endpoint to add a last_updated property to Redis. The new return format from these endpoints will look like
```
{"data": <data>, "last_updated": <last_updated>}
```

SenNet reference: https://github.com/sennetconsortium/ingest-api/pull/450/files However, we **won't** introduce those decorators and job queue features to HuBMAP, for now.

**Comment by ChuckKollar** [comment]
Only the second part has been done here. The first part has been moved to a new card https://github.com/orgs/hubmapconsortium/projects/40/views/1?pane=issue&itemId=68906593
