### ISSUE TITLE
Generate metadata.json files for processed datasets

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#575]
Currently metadata.json files are generated for primary datasets only, change this so metadata.json file are additionally generated for processed datasets where `creation_action == 'Central Process' or 'Lab Process' or 'External Process'` but not for multi-assay component datasets (component datasets match `creation_action == 'Multi-Assay Split`)

**Comment by libpitt** [comment]
@shirey @yuanzhou 
We looked on the ingest-api of SN and looks like we already have this handled within `publish_datastage` method which looks like ported over method from HM. We tweaked ours a bit and added a check for the component datasets.

[Here's the HM. ](https://github.com/hubmapconsortium/ingest-api/blob/main/src/app.py#L1130)


cc @maxsibilla

**Comment by ChuckKollar** [comment]
The current code clearly only writes metadata.json files for datasets which have no parents.

However, I have changed it to work according to the description given by Bill in the task description above.

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/ingest-api/pull/586

**Comment by shirey** [comment]
@ChuckKollar In testing, I'm trying to publish central processed dataset `59e8b98ce6094e0b73c627edb5b00a09` on TEST-  I'm seeing this error:

```
[2024-07-10 15:14:58] ERROR in app: local variable 'entity_dict' referenced before assignment
Traceback (most recent call last):
  File "/usr/src/app/src/./app.py", line 1130, in publish_datastage
    if is_primary or metadata_json_based_on_creation_action(entity_dict.get('creation_action')):
UnboundLocalError: local variable 'entity_dict' referenced before assignmen
```

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/ingest-api/pull/590

**Comment by ChuckKollar** [comment]
Bill says that he has found some problems and asked for a diff of the code and to checkout a "derived dataset on dev".
