### ISSUE TITLE
Generate metadata.json files for existing processed datasets

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#576]
For all existing Published, processed datasets including Central Processed, Lab Processed and EPIC (External) processed datasets, generate a metadata.json file.

See #575 for details of which datasets match these processed datasets.

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/ingest-api/pull/591

**Comment by ChuckKollar** [comment]
Tested on TEST, output:

Dataset UUID: 14bdcb4233490eb8586c78c8b1a48213 has no samples; Proceeding...
Dataset UUID: 2f8d43199ca3167e991b320038024b77 has no samples; Proceeding...
Dataset UUID: ca3016d836d8ee50bef1b93f339c9679 has no samples; Proceeding...
Dataset UUID: a61523fefe63ff37760a30ff34e53b5f has no samples; Proceeding...
Dataset UUID: f2e3357fec56d65731ebd76ccf8758d0 has no samples; Proceeding...
Files written: 1073
Done!
