### ISSUE TITLE
Add wave 3 + HCA data providers

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#62]

**Comment by shirey** [comment]
Add Data Providers for Wave 3 plus HCA to ingest-ui/ingest-api/entity-api/commons per https://docs.google.com/spreadsheets/d/1BLXxy8hOv13W1JFTzXb3L7EoaitqWig6GnrOCaSee78/edit?usp=sharing

**Comment by yuanzhou** [comment]
Will also need to create the UUID dir on PSC file system

**Comment by yuanzhou** [comment]
@shirey in addition to all the 11 newly added data providers, I also noticed that the `displayname` of **University of California San Diego TMC** is renamed to **University of California San Diego TMC focusing on kidney**. Are we supposed to renamed the directory name on the PSC file system too?

**Comment by yuanzhou** [comment]
Changed back to old `displayname`: **University of California San Diego TMC** via https://github.com/hubmapconsortium/commons/commit/da9b1494332250bded832f0987721893c68b69a9

**Comment by shirey** [comment]
This needs to be fully tested against users with all types of group memberships.  A blip was noticed by Zhou when, possibly, a user is a member of a single lab/data provider group and the data admin group.
