### ISSUE TITLE
Derived datasets with multiple parents not registered correctly

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#89]
When a derived dataset with multiple parents is created from an analysis pipeline only one dataset is registered as a parent.  This is via the ingest-api `datasets/derived` POST call.

From Joel:
[2021-07-02 21:11:12,892] {logging_mixin.py:120} INFO - {'derived_dataset_name': 'salmon_rnaseq_snareseq__4038c7a3510b38f0cd036aa4955246eb_af3e387f2441f172cbe7de29ea5c3c16_1e56c595c3f0e1cf126a80e00fd31c54_45aadbf99c097775e6004a978b5a731b_8fcb96b98c87178e2666435a3b3a5350_bbe9f1a95a61f32656ed4452fed9d424_eb7483e17dc656d065ed2c1595663998__salmon-rnaseq-snareseq',
 'derived_dataset_types': ['salmon_rnaseq_snareseq'],
 'source_dataset_uuid': ['4038c7a3510b38f0cd036aa4955246eb',
                         'af3e387f2441f172cbe7de29ea5c3c16',
                         '1e56c595c3f0e1cf126a80e00fd31c54',
                         '45aadbf99c097775e6004a978b5a731b',
                         '8fcb96b98c87178e2666435a3b3a5350',
                         'bbe9f1a95a61f32656ed4452fed9d424',
                         'eb7483e17dc656d065ed2c1595663998']}
[2021-07-02 21:11:12,894] {base_hook.py:89} INFO - Using connection to: id: ingest_api_connection. Host: hivevm193.psc.edu, Port: 7777, Schema: , Login: None, Password: None, extra: None
[2021-07-02 21:11:12,897] {http_hook.py:136} INFO - Sending 'POST' to url: http://hivevm193.psc.edu:7777/datasets/derived
[2021-07-02 21:11:13,799] {logging_mixin.py:120} INFO - response:
[2021-07-02 21:11:13,799] {logging_mixin.py:120} INFO - {'derived_dataset_uuid': '33c0ce043ae331ea23fc80023428e534',
 'full_path': '/hive/hubmap/data/consortium/University of California San Diego '
              'TMC/33c0ce043ae331ea23fc80023428e534',
 'group_display_name': 'University of California San Diego TMC',
 'group_uuid': '03b3d854-ed44-11e8-8bce-0e368f3075e8'}
[2021-07-02 21:11:13,939] {python_operator.py:114} INFO - Done. Returned value was: /hive/hubmap/data/consortium/University of California San Diego TMC/33c0ce043ae331ea23fc80023428e534

**Comment by yuanzhou** [comment]
@shirey and @jswelling when we initially added the functionality for creating derived dataset, we used `source_dataset_uuid` which was supposed to be just a single source dataset. Looking at the airflow logging, there are multiple source datasets are being sent from ingest-pipeline to ingest-api. That's why only the first one gets used to create the derived dataset.

- Should we renamed the field to `source_dataset_uuids` and require the input to be a list of uuids? Of course there can be only one source uuid in the list.
- ingest-pipeline only uses this at: https://github.com/hubmapconsortium/ingest-pipeline/search?q=source_dataset_uuid. If we don't want to make any changes in ingest-pipeline, I can tweak the code of ingest-api to accept either a single source uuid string or a list of uuids.

**Comment by yuanzhou** [comment]
Fixed and redeployed on DEV with 
- renaming from `source_dataset_uuid` to `source_dataset_uuids`
- supporting either a single uuid string or an array of uuids

**Comment by yuanzhou** [comment]
Query to list all datasets with this issue:
```
MATCH (parent:Entity)-[in:ACTIVITY_INPUT]->(a:Activity)-[out:ACTIVITY_OUTPUT]->(child:Dataset) 
WITH count(out) as out_cnt, child as c
WHERE out_cnt > 1
RETURN c.uuid, out_cnt
```

**Comment by yuanzhou** [comment]
Script to fix the above datasets: https://github.com/hubmapconsortium/manual-data-ingest/pull/43

**Comment by jswelling** [comment]
@jswelling please remember to test this. -me

**Comment by yuanzhou** [comment]
Tested and verified using Postman by making a call against ingest-api on DEV and TEST to mock the airflow call. The results look correct.

**Comment by yuanzhou** [comment]
The datasets fixed on the current PROD:
| c.uuid                           | c.created_by_user_displayname | cnt |
| -------------------------------- | ----------------------------- | --- |
| 67c33d9b27707bd87419025bf7fec43c | HuBMAP Process                | 6   |
| ef5c58d023711cf9ae73b73e616543e0 | HuBMAP Process                | 7   |
| 02809d1028ddf24a3d96cddd28ada2c7 | HuBMAP Process                | 6   |
| 4a5b7a2911ee622b7e48e4f65db42347 | HuBMAP Process                | 7   |
| ae1cf3212a4e98bfa807db7c9e4c20de | HuBMAP Process                | 3   |
| 95759f85b38cb22fb97301fefbdaae75 | HuBMAP Process                | 7   |
| 25ae35f5539ea01ac311a6ed006ab905 | HuBMAP Process                | 7   |
| 16784f68e919aeebfb0addaaa4f0cecb | HuBMAP Process                | 7   |
| cb22b7da3c456837e891465b03e4cff5 | HuBMAP Process                | 6   |
| 509b3821bc940d995565adcadbfa83e6 | HuBMAP Process                | 4   |
| 482e677b1d4617cc056f99631cb93b66 | HuBMAP Process                | 6   |
| 7f06c94b5ccf98770c51e276b8419477 | HuBMAP Process                | 7   |
| 52fc140cd05660f848cb851747578ab2 | HuBMAP Process                | 4   |
| 476b96c05609dead5d158d665f6c586a | HuBMAP Process                | 6   |
| 129a1af0945329917a8bb20aacd561c4 | HuBMAP Process                | 4   |
| 03c14df167479ce4326f0e818437ab32 | HuBMAP Process                | 4   |
| 4e0db07bfcc7b36e195a67cbdc48ed9e | HuBMAP Process                | 3   |
| 6c6f4c91395c0b119b1c7ea7a3bdf891 | HuBMAP Process                | 4   |
| f5f222b8aab5f881b6d280ae6c5ac719 | HuBMAP Process                | 3   |
| 33c8d9d47611f8f02ff52a9b5bc5eaf1 | HuBMAP Process                | 6   |
| 823d962c67abe030ac8415052c9ea498 | HuBMAP Process                | 6   |
| 053e22db35108fe558d1ad47ba479c3d | HuBMAP Process                | 4   |
| 71486e5c68036a4ced5fa238e359f30f | HuBMAP Process                | 6   |
| f8b63c64435fc6ad3bf8530faec8e9ad | HuBMAP Process                | 7   |
| c6d668e081c9fdbdf6f927996ec1cf58 | HuBMAP Process                | 4   |
| 735687fc65e9b3a033334c9c0caffee3 | HuBMAP Process                | 6   |
| 987ff64aeefaeca62568334aa94a9a58 | HuBMAP Process                | 4   |
| ea384ce4df06b77bf9ce130cdf4a7335 | HuBMAP Process                | 6   |
| 9a96490967e7b5e4f33bb8ba152e2779 | HuBMAP Process                | 4   |
| b5d7cb1e27afa0c97808984d48a8d5b4 | HuBMAP Process                | 6   |
| d4a25576341fde5a8fd81e26b097ab06 | HuBMAP Process                | 4   |
| 060a6d6b7c1aca10612f38f66892da14 | HuBMAP Process                | 4   |
| 36538f96467725031b5fd5eee2e95d98 | HuBMAP Process                | 6   |
| a51870fde54152df2cad6a98ddcd0b34 | HuBMAP Process                | 7   |
| 27ec8e368d3e5427f1f9d5015676ad24 | HuBMAP Process                | 4   |
| c66552ff89678bf21e32e78d3f012a5c | Liz McDonough                 | 26  |
| 59f249caa2fe225f030205c2abd86051 | Liz McDonough                 | 26  |
| c8c9873c9041b3bc3b75fb71f887e1c0 | Liz McDonough                 | 26  |
| 0ca0721ae67b78b5eed7c0ef20dc6ac1 | Liz McDonough                 | 26  |
| ec85791b4b73e76bf32bb40bad60fb50 | Liz McDonough                 | 26  |
| 6c75548f017fe5891f2ddc91566565f0 | Liz McDonough                 | 26  |
| 060dfa0fdf2b840864f62d2cd1a7a456 | Liz McDonough                 | 26  |
| ce30489adeb0c18b028055b8b60707ca | Liz McDonough                 | 26  |
| 215f1050fc286dcc579edfd9c2494de1 | Liz McDonough                 | 26  |
| 72b0dc83701c045d954b457baed40697 | Liz McDonough                 | 26  |
| fa238ec2a83302fb4af92442c3683a23 | Liz McDonough                 | 26  |
| 65e850415322baad58626e3a228478dc | Liz McDonough                 | 26  |
