### ISSUE TITLE
File uploads for AVR

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#96]
When AVR records are created a report in PDF or Word format will be provided.  We need to use the standard `ingest-api` file upload infrastructure (`file-upload` & `file-commit`)  to load these files and expose them via the assets service.

- Make any changes needed to allow a file parent to be an AVR (AVR uuids are generated by UUID service, but not tracked in Neo4j) with open access (no token ever required to access the AVR)
 - Coordinate with the NuRelm group so they use this service when loading AVR files.

**Comment by yuanzhou** [comment]
Summary:
- Bill added AVR support in uuid-api, I'll get it merged into `test-release` and later redeployed on both DEV and TEST
- The antibody-api will call uuid-api to generate the AVR uuid by specifying `entity_type` as "AVR"
- The antibody-api calls the standard `/file-upload` in ingest-api to upload the AVR PDF and get back the `temp_file_id`
- The antibody-api calls `/file-commit` by sending over the `temp_file_id`, `entity_uuid` (AVR uuid generated from previous step) and the user token to commit the AVR PDF. 
- The assets linkage will be created like usual

When querying the AVR PDF via the assets file serivice:
- GET https://assets.test.hubmapconsortium.org/<avr-file-uuid>/avr-filename.pdf
- The gateway will call uuid-api to retrieve this file-uuid first
- If the ancestor type is `AVR`, access is public, no token needed
